---
- name: NFS Server Setup and Export
  hosts: nfs_server
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Install NFS server dependencies
      ansible.builtin.yum:
        name:
          - nfs-utils
          - rpcbind
        state: present

    - name: Ensure NFS services are enabled and running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - nfs-server
        - rpcbind

    - name: Create export directories on NFS server
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop: "{{ nfs_directories }}"

    - name: Configure NFS exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ item.path }} {{ item.clients }}"
        create: yes
      loop: "{{ nfs_directories }}"

    - name: Export NFS shares
      ansible.builtin.command: exportfs -ra
      args:
        warn: false

- name: NFS Client Setup and Mount
  hosts: nfs_clients
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Install NFS client dependencies
      ansible.builtin.yum:
        name: nfs-utils
        state: present

    - name: Ensure mount directories exist on NFS client
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop: "{{ mount_directories }}"

    - name: Mount NFS shares on client
      ansible.builtin.mount:
        path: "{{ item.path }}"
        src: "{{ nfs_server_ip }}:{{ item.path }}"
        fstype: nfs
        opts: rw
        state: mounted
      loop: "{{ mount_directories }}"
