- name: Playbook for Multi-disk LVM Creation
  hosts: all
  become: true
  vars_files:
    - multidiskcreatevar.yaml
  tasks:
    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present

    - name: Get disk information
      shell: "ls -ll /dev/disk/by-id/google-{{ item.disk_id }} | awk '{print $NF}' | awk -F '/' '{print $NF}'"
      register: disk_info
      loop: "{{ lvm_configs }}"

    - name: Create volume groups
      lvg:
        vg: "{{ item.item.vg_name }}"
        pvs: "/dev/{{ item.stdout }}"
        pesize: 16
      loop: "{{ disk_info.results }}"

    - name: Create logical volumes
      lvol:
        vg: "{{ item.vg_name }}"
        lv: "{{ item.lv_name }}"
        size: "{{ item.size | default('100%FREE') }}"
        force: yes
      loop: "{{ lvm_configs }}"

    - name: Create directory mountpoints
      file:
        path: "{{ item.mount_dir }}"
        state: directory
        mode: '0777'
      loop: "{{ lvm_configs }}"

    - name: Format filesystems
      filesystem:
        fstype: "{{ item.fs_type | default('xfs') }}"
        dev: "/dev/{{ item.vg_name }}/{{ item.lv_name }}"
      loop: "{{ lvm_configs }}"

    - name: Mount filesystems
      ansible.posix.mount:
        path: "{{ item.mount_dir }}"
        src: "/dev/{{ item.vg_name }}/{{ item.lv_name }}"
        fstype: "{{ item.fs_type | default('xfs') }}"
        state: mounted
      loop: "{{ lvm_configs }}"
