---
- name: RHEL OS Patching Automation
  hosts: linux
  become: yes
  gather_facts: yes

  tasks:

    - name: Show OS information
      debug:
        msg: "Patching {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Check if subscription-manager exists
      stat:
        path: /usr/sbin/subscription-manager
      register: submgr

    - name: Clean DNF cache
      command: dnf clean all

    - name: Rebuild DNF cache
      command: dnf makecache

    - name: Enable BaseOS repo
      command: subscription-manager repos --enable=rhel-9-baseos-rpms
      when: submgr.stat.exists

    - name: Enable AppStream repo
      command: subscription-manager repos --enable=rhel-9-appstream-rpms
      when: submgr.stat.exists

    - name: Enable CRB repo
      command: subscription-manager repos --enable=rhel-9-crb-rpms
      when: submgr.stat.exists

    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        nobest: yes
        skip_broken: yes
 
